- source/kernel/src/bbq.rs
> kernel: add `TRACE` spans to BBQueue methods

- source/melpomene/src/main.rs
This probably isn't the BEST way to do this, but given that the number of sleeps we will have is relatively low for now, this seems like a BETTER way to do this.
> Use a thread to sleep instead of busy polling

- .github/workflows/ci.yml
- source/abi/src/syscall/mod.rs
- source/mstd/src/lib.rs
- tools/crowtty/src/main.rs
- tools/dumbloader/src/main.rs
> Add first CI, will likely fail fmt check

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- rfcs/0000-driver-registry.md
- source/abi/Cargo.toml
- source/abi/src/syscall/mod.rs
- source/kernel/Cargo.toml
- source/kernel/src/comms/bbq.rs
- source/kernel/src/comms/kchannel.rs
- source/kernel/src/comms/mod.rs
- source/kernel/src/comms/oneshot.rs
- source/kernel/src/drivers/serial_mux.rs
- source/kernel/src/lib.rs
- source/kernel/src/registry/mod.rs
- source/melpomene/Cargo.toml
- source/melpomene/src/main.rs
- source/melpomene/src/sim_drivers/tcp_serial.rs
- source/mstd/Cargo.toml
- source/mstd/src/lib.rs
- source/spitebuf/src/lib.rs
- tools/crowtty/src/main.rs
- tools/dumbloader/src/main.rs
> RFC: Driver Registry

- rfcs/0000-a-forth-userspace.md
[Rendered](https://github.com/tosc-rs/mnemos/blob/2023-a-new-beginning/rfcs/0000-a-forth-userspace.md)
> RFC: a forth userspace

- source/kernel/src/comms/kchannel.rs
- source/kernel/src/lib.rs
- source/kernel/src/registry/mod.rs
- source/mstd/src/executor/mod.rs
- source/mstd/src/utils/mod.rs
- tools/crowtty/src/main.rs
@jamesmunns it's up to you whether we care about this. i'm also happy to just disable clippy in my VSCode workspace for mnemOS...
> fix various clippy warnings

- Cargo.toml
- source/alloc/tests/smoke.rs
- source/forth3/src/dictionary.rs
- source/forth3/src/vm/async_vm.rs
- source/melpomene/Cargo.toml
- source/melpomene/src/main.rs
> Fix warnings

- Cargo.lock
- Cargo.toml
- platforms/allwinner-d1/boards/lichee-rv/src/main.rs
- source/melpomene/src/main.rs
- source/melpomene/src/sim_drivers/emb_display.rs
Note: Don't merge until (at least) I revert all the `warn!()` tracing messages.
> Make kernel event loop more consistent

- tools/crowtty/src/main.rs
This commit adds a small additional indicate to `crowtty`'s logs to show whether the target connection is over TCP serial or over the UART.
> feat(crowtty): logs indicate if target is TCP/UART

- tools/crowtty/src/trace.rs
This commit changes the `crowtty` trace format slightly so that it's a closer match to the `tracing_subscriber::fmt` format used by Melpomene. This, admittedly, does not actually matter at all, but I wanted to do it.
> feat(crowtty): make trace format match melpomene

- source/melpomene/src/main.rs
I meant to merge this as part of #99, but accidentally merged that branch without pushing this commit. Whoopsie!
> feat(melpo): add spans to sim drivers

- .github/workflows/ci.yml
- Cargo.lock
- justfile
- platforms/allwinner-d1/boards/Cargo.lock
- platforms/allwinner-d1/core/Cargo.toml
I noticed some of the `just` tasks were broken due to d1-core changes.
> Do some stuff with just

- source/kernel/src/daemons/shells.rs
- source/kernel/src/services/forth_spawnulator.rs
- source/kernel/src/services/serial_mux.rs
- source/melpomene/src/main.rs
This PR adds a helper daemon for spawning a shell on a sermux port
> feat(kernel): Add sermux shell daemon

- platforms/allwinner-d1/boards/src/bin/lichee-rv.rs
I uh, left this in while testing the panic code in #123. It generally shouldn't do that.
> Remove some residual testing code

- Cargo.lock
- platforms/allwinner-d1/boards/Cargo.lock
- source/kernel/Cargo.toml
- source/trace-proto/Cargo.toml
- tools/crowtty/Cargo.toml
This changes the HashMap used for fields into a BTreeMap for deterministic field ordering
> feat(trace-proto): Update branch of tracing-serde-structured

- platforms/allwinner-d1/core/src/drivers/twi.rs
The `A_ACK` bit is only supposed to be set when reading bytes from the TWI when operating as the bus controller. And, it's supposed to be disabled *before* reading the final byte of the read, so that the last byte gets NAKed. We weren't doing that last thing correctly for multi-byte reads, due to a wrong comparison (sorry). This branch fixes it.
In addition, I've removed some unneeded setting of `A_ACK` in a few places to ensure it's only set when it's supposed to be.
> fix(d1): fix wrong TWI `A_ACK` flag behavior

- platforms/allwinner-d1/core/src/drivers/sharp_display.rs
- source/alloc/src/containers.rs
- source/melpomene/src/sim_drivers/emb_display.rs
These seemed nice to have. Some of them were needed for implementing the keyboard driver.
> feat(alloc): add some more methods to `FixedVec`

- platforms/melpomene/src/sim_drivers/emb_display.rs
This PR adds support for sending keymux events from the simulator input.
Demo: 
https://github.com/tosc-rs/mnemos/assets/2097964/3f359f88-0585-4c46-b79b-0d46f730893b
> feat(melpo): Initial keyboard + keymux support

- platforms/melpomene/src/sim_drivers/emb_display.rs
This PR fixes a couple of incorrect key mappings after testing today.
> fix(melpo): Correct some key mappings

- Cargo.lock
- Cargo.toml
- platforms/allwinner-d1/boards/Cargo.lock
- platforms/allwinner-d1/boards/Cargo.toml
- platforms/allwinner-d1/core/src/drivers/sharp_display.rs
- platforms/allwinner-d1/core/src/drivers/spim.rs
- platforms/allwinner-d1/core/src/drivers/uart.rs
- platforms/allwinner-d1/core/src/lib.rs
- platforms/pomelo/Cargo.toml
- source/kernel/src/comms/bbq.rs
- source/kernel/src/comms/kchannel.rs
- source/kernel/src/comms/oneshot.rs
- source/kernel/src/lib.rs
- source/spitebuf/src/lib.rs
why the fuck doesn't this work
> use `WaitCell::subscribe`

- platforms/allwinner-d1/core/src/drivers/twi.rs
This changes most of the `tracing` events in the `twi` module from the `DEBUG` level to the `TRACE` level. When talking to I2C devices every ~50ms, this logging is *way* too verbose and drowns out basically everything else. Now, we only log every interrupt at TRACE.
> fix(d1): demote extremely verbose TWI ISR logging

- .github/workflows/ci.yml
- justfile
- platforms/allwinner-d1/boards/src/bin/lichee-rv.rs
- platforms/allwinner-d1/boards/src/bin/mq-pro.rs
- platforms/allwinner-d1/core/src/dmac/descriptor.rs
- platforms/allwinner-d1/core/src/dmac/mod.rs
- platforms/allwinner-d1/core/src/drivers/sharp_display.rs
- platforms/allwinner-d1/core/src/drivers/spim.rs
- platforms/allwinner-d1/core/src/drivers/uart.rs
- platforms/allwinner-d1/core/src/lib.rs
- platforms/allwinner-d1/core/src/plic.rs
- platforms/melpomene/src/sim_drivers/tcp_serial.rs
- platforms/pomelo/src/sim_drivers/serial.rs
- source/alloc/src/containers.rs
- source/alloc/src/heap.rs
- source/forth3/src/input.rs
- source/forth3/src/leakbox.rs
- source/forth3/src/lib.rs
- source/forth3/src/testutil/mod.rs
- source/forth3/src/vm/async_vm.rs
- source/forth3/src/vm/mod.rs
- source/kernel/src/daemons/sermux.rs
- source/kernel/src/daemons/shells.rs
- source/kernel/src/forth/mod.rs
- source/kernel/src/registry/mod.rs
- source/kernel/src/services/emb_display.rs
- source/kernel/src/services/forth_spawnulator.rs
- source/kernel/src/services/serial_mux.rs
- source/sermux-proto/src/lib.rs
- tools/crowtty/src/main.rs
Note that some of these lints required non-trivial refactoring to fix. @jamesmunns, wdyt?
> style: fix all clippy lints and add clippy to CI

- platforms/allwinner-d1/README.md
As we discussed in the chat, it would be good to have an explanation about what happens on boot for the D1.
This PR adds my understanding of the flow.
> Add 'boot procedure' section to platforms/allwinner-d1/README.md

- platforms/README.md
> docs: fix broken links in `platforms/README.md`

- scripts/install-ci-deps.sh
This PR tries to fix netlify CI again
> bug(docs): fix netlify CI

- platforms/melpomene/melpo-config/src/lib.rs
- platforms/melpomene/melpo.toml
- platforms/melpomene/src/sim_drivers/emb_display.rs
This PR makes UI scaling a config file option
> feat(melpo): Makes scaling an option

- scripts/rfc2book.py
> docs: nest RFCs in their own section

- platforms/melpomene/src/main.rs
- source/kernel/src/daemons/shells.rs
This PR introduces smarter debouncing of GUI shell redraws, by first waiting "forever",
then waiting with a timeout.
Closes #255
> feat(kernel/daemons/shell): Smarter redraw debouncing

- platforms/allwinner-d1/d1-core/src/clint.rs
- platforms/allwinner-d1/d1-core/src/drivers/sharp_display.rs
- platforms/allwinner-d1/d1-core/src/plic.rs
- source/abi/src/bbqueue_ipc/bbbuffer.rs
basically all of these are related to doc comments in various ways. to
which i generally say: "who cares?"
> style: fix a pile of "dumb but fair" clippy lints
